
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AXISX AXISY BAR COMMA DIVIDE EQUALS EXPONENT EXPRNAME LINE LPARENT MINUS NUMBER PLOT PLUS PRINT QUOTATION RPARENT SHOWTEXT TIMES TITLEtitle : TITLE EQUALS SHOWTEXTprint : PRINT TITLE'
    
_lr_action_items = {'TITLE':([0,],[2,]),'$end':([1,4,],[0,-1,]),'EQUALS':([2,],[3,]),'SHOWTEXT':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'title':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> title","S'",1,None,None,None),
  ('title -> TITLE EQUALS SHOWTEXT','title',3,'p_title','lex.py',135),
  ('print -> PRINT TITLE','print',2,'p_print_title','lex.py',141),
]
